### ISSUE TITLE
BrowserConnector doesn't able to pair

### ISSUE THREAD

**Issue by bachig26** [sylviiu/ezytdl-browser-connector#1]
I'm using the [latest nightly build of qzytdl 3.0.0-dev.147](https://github.com/sylviiu/ezytdl/releases/tag/3.0.0-dev.147) and the [latest connector nightly build 20](https://github.com/sylviiu/ezytdl-browser-connector/releases/tag/20) in my Windows and Vivaldi Browser.

I have Generated the Pair key by clicking the `Generate` button and tried to pair via the extension but can't connect.

In the Inspect views: it shows the `service worker (Inactive)`.

I'm getting couple errors and provided below, please let know how to fix it and possible solution. Thank you.

### Errors:

1. **WebSocket connection to 'ws://localhost:38529/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**
```
### Context:

          connection.js

### Stack Trace:

          connection.js:65 (anonymous function)
from line 65: const socket = new WebSocket(`ws://localhost:38529`);

```

2. **Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status')**
```
### Context:

          html/index.html

### Stack Trace:

         ui.js:181 (anonymous function)
from line 181: if(vars.state.status != previousState) {
```

**Comment by bachig26** [comment]
@sylviiu this is my 1st time using the app, so I'm confused and never tried similar app and extension pairing system.

**Comment by sylviiu** [comment]
It's no worries! This is the first time I've made anything like this, so it's definitely not guaranteed to be perfect haha.

Have you enabled the browser connector option near the top of the settings page?

**Comment by sylviiu** [comment]
I'll download Vivaldi on my side to test out the functionality there, too.

**Comment by bachig26** [comment]
> Have you enabled the browser connector option near the top of the settings page?

I think so yes.

**Comment by sylviiu** [comment]
I was able to connect successfully using Vivaldi, so there isn't any compatibility issues for that.

"ERR_CONNECTION_REFUSED" typically means that the server it's trying to connect to (in this case, the app) is offline.

Please do make sure this option in the settings of the app is enabled. The server is only started when this option is enabled (and saved).
![image](https://github.com/sylviiu/ezytdl-browser-connector/assets/95180094/8ff40b7d-0115-4e81-ba4f-8ef4261dca51)

**Comment by bachig26** [comment]
> Please do make sure this option in the settings of the app is enabled. The server is only started when this option is enabled (and saved). ![image](https://user-images.githubusercontent.com/95180094/261164025-8ff40b7d-0115-4e81-ba4f-8ef4261dca51.png)

thanks, i remember enabling this. but when i re-installed the app and i found it was not enabled at all. maybe i forgot.

**Comment by sylviiu** [comment]
It's no worries! Glad it's working :D
